# Generated by Django 4.0.3 on 2022-04-06 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_item_options_item_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
